# Generated by Django 5.1 on 2025-02-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footballarenaimage",
            options={
                "ordering": ("arena", "order"),
                "verbose_name": "Football Arena Image",
                "verbose_name_plural": "Football Arena Images",
            },
        ),
        migrations.RenameField(
            model_name="footballarenaimage",
            old_name="area",
            new_name="arena",
        ),
    ]
