# Generated by Django 5.1 on 2025-02-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("area", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footballareaimage",
            options={
                "ordering": ("area", "order"),
                "verbose_name": "Football Area Image",
                "verbose_name_plural": "Football Area Images",
            },
        ),
    ]
